# Generated by Django 5.2.7 on 2025-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('voice', 'Voice Training'), ('conversation', 'Camera Conversation')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('feedback_text', models.TextField(blank=True)),
                ('repeated_words', models.PositiveIntegerField(default=0)),
                ('mispronunciations', models.PositiveIntegerField(default=0)),
                ('facial_feedback_score', models.FloatField(default=0.0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
