# Generated by Django 5.2.7 on 2025-10-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
