# Generated by Django 5.2.7 on 2025-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0002_trainingsession_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
