# Generated by Django 5.2.7 on 2025-10-28 23:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0004_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='progressanalytics',
            name='best_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progressanalytics',
            name='total_training_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressanalytics',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress_analytics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressanalytics',
            name='worst_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='confidence_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='engagement_level',
            field=models.CharField(choices=[('disengaged', 'Disengaged'), ('neutral', 'Neutral'), ('engaged', 'Engaged')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='eye_contact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.CharField(blank=True, default='SpeakEase Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='facial_feedback_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_type',
            field=models.CharField(choices=[('voice', 'Voice Training'), ('conversation', 'Camera Conversation'), ('tips', 'Tips & Motivation')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('total_training_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
