# Generated by Django 5.2.7 on 2025-10-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0005_vocabularyword_alter_tip_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('social', 'Social')], default='personal', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
