# Generated by Django 5.2.7 on 2025-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0006_dailyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
    ]
