# Generated by Django 5.2.7 on 2025-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakEase_backend_app', '0007_trainingsession_transcribed_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQuestion',
        ),
        migrations.RemoveField(
            model_name='progressanalytics',
            name='improvement_rate',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='engagement_level',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='eye_contact_score',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='facial_feedback_score',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_type',
            field=models.CharField(choices=[('voice', 'Voice Training'), ('tips', 'Tips & Motivation')], max_length=20),
        ),
    ]
